### ISSUE TITLE
Unicode player names break parsing

### ISSUE THREAD

**Issue by TcT2k** [danielsamuels/rocket-league-replays#1]
When player names contain unicode characters replay parsing fails.

In `rocket_league/utils/replay_parser.py` when reading string propertys (and name properties) after reading the string length values < 0 indicate a unicode string.

**Comment by danielsamuels** [comment]
That's odd, I thought I'd fixed all of the unicode issues in 926cae570c35f33a6a687d9fc7d42457735d32ab. I'll generate some new replay files and double check this.

**Comment by TcT2k** [comment]
I just assumed it was the unicode playername that caused the upload error. I'll send you the file in case you can't reproduce the issue.

**Comment by danielsamuels** [comment]
Feel free to attach it regardless, it's always useful to have test cases for these sorts of things!

**Comment by TcT2k** [comment]
ZIPs don't seem to be possible to attach but the file is [here](https://tc84.net/owncloud/index.php/s/7xOOLz7p2tVM5wq). I've tried uploading the unzipped version.

**Comment by danielsamuels** [comment]
Hmm, that file doesn't exist apparently. Perhaps try renaming it to .jpg and uploading it here again?

**Comment by TcT2k** [comment]
Next try with [Google Drive](https://drive.google.com/file/d/0B0F_dHgLjGPNZUN6TU1TUXJjNG8/view?usp=sharing) :)

**Comment by danielsamuels** [comment]
Got it! Thanks!

**Comment by danielsamuels** [comment]
I think he has null bytes in his username. Surely not? :D

**Comment by TcT2k** [comment]
It's a UTF-16 string. The string length is negative to mark this (-9). I've one other replay where a player has a UTF-16 string just like this one. In RLReplayManager I just negate the length and read x number of UTF-16 characters instead of the normal UTF-8 (or latin?) when a positive length is used.

**Comment by danielsamuels** [comment]
Hmm, it seems like there's been quite a few changes to the replay structure so a fair amount of the parser is now not working correctly. This is going to take longer to fix than I'd hoped. :disappointed:

**Comment by danielsamuels** [comment]
Fixed in danielsamuels/rocket-league-replay-parser@f92eb72ba48d3726700c572ff56e6bf6405200c2. Thanks for the report!
